### PR TITLE
Remove `UnTagged`

### PR DESCRIPTION
**Pull request by OliverJAsh**
Fixes https://github.com/pelotom/unionize/issues/61

### CODE REVIEW

**Comment by OliverJAsh** [comment]
@pelotom What's your release process? I'm happy to give it a go. I may need npm access too though.

**Comment by pelotom** [comment]
> @pelotom What's your release process? I'm happy to give it a go.

```
yarn build
yarn publish
```

> I may need npm access too though.

Yeah I'd guess so 😄 What's your NPM username?

**Comment by OliverJAsh** [comment]
oliverjash

**Comment by pelotom** [comment]
K, you should be added.

**Comment by OliverJAsh** [comment]
Released in v3.0.2 to npm.

@pelotom What's the process for updating https://github.com/pelotom/unionize/releases, if there is one?

**Comment by pelotom** [comment]
Currently I just go in and manually create a release describing and linking to the features/bugfixes.

**Pull request merged**
