### PR TITLE
More precise variant typing fixes #7

### LINKED ISSUE #7: More precise typing of variants.
When instantiating one variant of a union, it is typed as the type of the union.
It would be nicer to have the actual narrower type of the variant.

To achieve this, one could change the signature of Creators from
```typescript
export type Creators<Record, TaggedRecord> = {
  [T in keyof Record]: (value: Record[T]) => TaggedRecord[keyof TaggedRecord]
}
```

to

```typescript
export type Creators<Record, TaggedRecord> = {
  [T in (keyof Record & keyof TaggedRecord)]: (value: Record[T]) => TaggedRecord[T]
}
```

any chance to get that in?

### PR DESCRIPTION
**Pull request by sledorze**

### CODE REVIEW

**Comment by pelotom** [comment]
Ok, here's a practical example of the sort of inference problem [I alluded to](https://github.com/pelotom/unionize/issues/7#issuecomment-329295739):

```ts
const State = unionize({
  loading: {},
  loaded: ofType<{ x: number }>(),
})
type State = typeof State._Union

const Action = unionize({
  REQUEST: ofType<{ slug: string }>(),
  RECEIVE: ofType<{ x: number }>(),
}, 'type')
type Action = typeof Action._Union

const reducer = (state = State.loading({}), action: Action) =>
  Action.match({
    REQUEST: () => state,
    RECEIVE: State.loaded,
  })(action)
```

This works fine when the variant creators produce values of the union type, but with your change the body of the reducer no longer type checks:

```
src/index.ts(140,16): error TS2345: Argument of type '{ REQUEST: () => { tag: "loading"; }; RECEIVE: (value: { x: number; }) => { tag: "loaded"; } & { ...' is not assignable to parameter of type 'Cases<{ REQUEST: { slug: string; }; RECEIVE: { x: number; }; }, "REQUEST" | "RECEIVE", { tag: "lo...'.
  Types of property 'RECEIVE' are incompatible.
    Type '(value: { x: number; }) => { tag: "loaded"; } & { x: number; }' is not assignable to type '(value: { x: number; }) => { tag: "loading"; }'.
      Type '{ tag: "loaded"; } & { x: number; }' is not assignable to type '{ tag: "loading"; }'.
        Types of property 'tag' are incompatible.
          Type '"loaded"' is not assignable to type '"loading"'.
```

Maybe this is a bug in TypeScript; it certainly seems like it should be able to unify this better, but until it can do a better job I don't think I want to change this typing.

**Comment by sledorze** [comment]
@pelotom It's not a bug of the compiler, it's completely normal.

_That's the reason why cats and scalaz have introduced some specific function in order to have 'some' and 'none' creating the Option type and not Some or None types._

My use case was the opposite, I am instantiating a value and want to take advantage of typescript control flow for typesafety.

With the current behavior I have to artificially manage the case the value is not of the type I've use to create it (which adds artificial complexity).

So there's two (I think valid) use cases and don't want to either choose between one or the other.
Should we expose two different sets of ctors?

Like 
```typescript
State.loading({})
```

and 

```typescript
State.keyword.loading({})
```
`keyword` being a placeholder there to specify either a broader or narrower type.

What do you think?

**Comment by pelotom** [comment]
I'm open to adding a `State.keyword.loading(...)` method for obtaining the more specific variant type, but I admit I still don't understand why this is useful. It seems like you can trivially obtain whatever the `...` was you passed into the creator by just extracting it to a variable first, i.e.

```ts
const payload = ...
const state = State.loading(payload)
doSomethingWithSpecificType(payload)
```

I'm curious to see a concrete use case where extra API to make this already simple thing even simpler would be helpful; so far none have cropped up in my own projects.

I also find a certain aesthetic cleanliness in the variant constructors producing values of the union type; it feels closer to the type theoretic notion of a sum type and how such things work in the pure FP languages. But that's not a serious objection 😄

**Comment by sledorze** [comment]
That's a legitimate question.
I am currently implementing a CQRS framework where for which, in each Aggregate type, I create a union of Events and one of the Commands related to that aggregate.

In order to be able to specify the possible exchanges between aggregates and process manager (if you know CQRS a bit), I express for each Command an aggregate receive what specific events can be created.
(I have a eDSL in which each combinator generate both the type I will need to implement in the final Aggregate code AND an ast with which I will be able to do state searching.

So from that machinery I can deduce the possible indirect Events / Commands creation in the system.
My goal is to ensure some invariance regarding the processing (like progress, termination, etc..).

When I use unionize in its current form, I get, for each Command, the type of Union of all Events as possible outcome, whereas with the modiication I propose, I get only the real subset of it, enabling the typechecking I'm after.

I know how things work in pure FP/ML language, in which the feature has to be implemented that way.
In typescript we have the opportunity for type narrowing, I find interesting to give the ability to use that *different* expressivity power.

**Comment by pelotom** [comment]
I'm not familiar with CQRS, but maybe a code example would help...

**Comment by sledorze** [comment]
Here's an example of code using the specific combinators I told you about to generate both the Type and AST:

```typescript
const bookCommandHandler = (aggregateId: AggregateId) =>
  p.fun({
    param: p.pureTyped(
      commands.book({
        id: aggregate.newCommandId.book(),
        aggregateId,
        timestamp: new Date(Date.now()),
        by: 'xx',
        atPrice: 123
      })),
    result: ({ value: cmd }) => p.and([
      p.pureTyped(events.booked({
        id: aggregate.newEventId.booked(), aggregateId, timestamp: cmd.timestamp, atPrice: cmd.atPrice
      })),
      p.pureTyped(events.bookRejected({
        id: aggregate.newEventId.bookRejected(), aggregateId, timestamp: cmd.timestamp, atPrice: cmd.atPrice
      }))
    ])
  })
```

the param field is the command.
the result field is the possibles events types ( here I use a `and`combinator)

This aggregate has a lot more Events, still I want the only the combinaison of booked or bookRejected to be infered.

Later this commandHandler is mixed with other, etc.. but that's not interesting with our issue.


Here's the 'and' combinator

```typescript

export type And<A extends AST[]> = {
  type: 'and',
  as: AST[]
}
function and<A extends ASTSpec, B extends ASTSpec>(as: [A, B]):
  Spec<[A['type'], B['type']], And<[A['ast'], B['ast']]>>;
function and<A extends ASTSpec, B extends ASTSpec, C extends ASTSpec>(as: [A, B, C]):
  Spec<[A['type'], B['type'], C['type']], And<[A['ast'], B['ast'], C['ast']]>>;
function and<A extends ASTSpec, B extends ASTSpec, C extends ASTSpec, D extends ASTSpec>(as: [A, B, C, D]):
  Spec<[A['type'], B['type'], C['type'], D['type']], And<[A['ast'], B['ast'], C['ast'], D['ast']]>>;
function and<A extends ASTSpec>(as: A[]):
  Spec<A['type'], And<(A['ast'][])>> {
  const type = <any>1
  const ast = makeAnd(as.map(x => x.ast))
  return ({
    type,
    ast
  })
}

```
The interesting part is
```typescript
Spec<[A['type'], B['type'], C['type'], D['type']], And<[A['ast'], B['ast'], C['ast'], D['ast']]>>
```
Where I infer a heterogeneous array in order to keep the specific types..
I the values passed to the and combinator are general, it will not reflect the AST and so the signature I can extract from that DSL won't help me implement the required exact function I typecheck with the AST.

**Comment by sledorze** [comment]
@pelotom by the way, here's an intro to CQRS (and Event sourcing) here:
https://www.youtube.com/watch?v=JHGkaShoyNs

**Comment by pelotom** [comment]
Your example is still too complicated for me to follow having no prior experience with this stuff. But it should be trivial to write a helper on top of `unionize` like this, no?

```ts
const Foo = unionize({
  x: ofType<{ foo: number }>(),
  y: ofType<{ bar: boolean }>(),
})
type Foo = typeof Foo._Union

function createRefined<K extends Foo['tag']>(
  k: K,
  payload: (typeof Foo._Record)[K]
): { tag: K } & typeof payload {
  return Foo[k](payload)
}

// result: { tag: "x" } & { foo: number }
const result = createRefined('x', { foo: 3 })
```

**Comment by pelotom** [comment]
Closing this as I haven't found the arguments for it compelling.

**Pull request closed without merging**
